export const ActList: Array<string> = [
    "Accountants Act",
    "Accounting and Corporate Regulatory Authority Act",
    "Accounting Standards Act",
    "Active Mobility Act 2017",
    "Administration of Justice (Protection) Act 2016",
    "Administration of Muslim Law Act",
    "Adoption of Children Act",
    "Advance Medical Directive Act",
    "Agency for Science, Technology and Research Act",
    "Air Navigation Act",
    "Allied Health Professions Act",
    "Amusement Rides Safety Act",
    "Animals and Birds Act",
    "Apostille Act 2020",
    "Application of English Law Act",
    "Apportionment Act",
    "Apportionment of Rents Act",
    "Appraisers Act",
    "Arbitration (International Investment Disputes) Act",
    "Arbitration Act",
    "Architects Act",
    "Arms and Explosives Act",
    "Arms Offences Act",
    "Asian Development Bank Act",
    "Asian Infrastructure Investment Bank Act",
    "Attorney-General (Additional Functions) Act",
    "Audit Act",
    "Banishment Act",
    "Banking Act",
    "Betting Act",
    "Betting and Sweepstake Duties Act",
    "Bills of Exchange Act",
    "Bills of Lading Act",
    "Bills of Sale Act",
    "Biological Agents and Toxins Act",
    "Bishop of Singapore Ordinance",
    "Boundaries and Survey Maps Act",
    "Boy Scouts Association Act",
    "Bretton Woods Agreements Act",
    "Broadcasting Act",
    "Brothers of St. Gabriel Ordinance",
    "Building and Construction Authority Act",
    "Building and Construction Industry Security of Payment Act",
    "Building Control Act",
    "Building Maintenance and Strata Management Act",
    "Bus Services Industry Act 2015",
    "Business Names Registration Act 2014",
    "Business Trusts Act",
    "Carbon Pricing Act 2018",
    "CareShield Life and Long-Term Care Act 2019",
    "Carriage by Air (Montreal Convention, 1999) Act",
    "Carriage by Air Act",
    "Carriage of Goods by Sea Act",
    "Casino Control Act",
    "Census Act",
    "Central Provident Fund Act",
    "Central Sikh Gurdwara Board Act",
    "Charities Act",
    "Chemical Weapons (Prohibition) Act",
    "Child Development Co-Savings Act",
    "Children and Young Persons Act",
    "Chit Funds Act",
    "Choice of Court Agreements Act",
    "Christian Brothers’ Schools Visitor Ordinance",
    "CISCO (Dissolution) Act",
    "Civil Aviation Authority of Singapore Act",
    "Civil Defence Act",
    "Civil Defence Shelter Act",
    "Civil Law Act",
    "Civil List and Gratuity Act",
    "Civil Service College Act",
    "Commodity Trading Act",
    "Common Gaming Houses Act",
    "Common Services Tunnels Act 2018 ",
    "Community Care Endowment Fund Act",
    "Community Disputes Resolution Act 2015",
    "Community Mediation Centres Act",
    "Companies Act",
    "Competition Act",
    "Compulsory Education Act",
    "Computer Misuse Act",
    "Constitution of the Republic of Singapore",
    "Consumer Protection (Fair Trading) Act",
    "Consumer Protection (Trade Descriptions and Safety Requirements) Act",
    "Contracts (Rights of Third Parties) Act",
    "Contributory Negligence and Personal Injuries Act",
    "Control of Essential Supplies Act",
    "Control of Manufacture Act",
    "Control of Plants Act",
    "Control of Vectors and Pesticides Act",
    "Conveyancing and Law of Property Act",
    "Co-operative Societies Act",
    "Copyright Act",
    "Coroners Act",
    "Corporate Bodies’ Contracts Act",
    "Corrosive and Explosive Substances and Offensive Weapons Act",
    "Corruption, Drug Trafficking and Other Serious Crimes (Confiscation of Benefits) Act",
    "Countervailing and Anti-Dumping Duties Act",
    "COVID-19 (Temporary Measures for Solemnization and Registration of Marriages) Act 2020",
    "COVID-19 (Temporary Measures) Act 2020",
    "Credit Bureau Act 2016",
    "Criminal Justice Reform Act 2018 ",
    "Criminal Law (Temporary Provisions) Act",
    "Criminal Law Reform Act 2019",
    "Criminal Procedure Code",
    "Cross-Border Railways Act 2018 ",
    "Currency Act",
    "Customs Act",
    "Cybersecurity Act 2018",
    "Dangerous Fireworks Act",
    "Daughters of Charity of the Canossian Institute Incorporation Ordinance",
    "Debtors Act",
    "Decorations and Uniforms Act",
    "Deep Seabed Mining Act 2015",
    "Defamation Act",
    "Defence Science and Technology Agency Act",
    "Dental Registration Act",
    "Departmental Titles (Alteration) Act",
    "Deposit Insurance and Policy Owners’ Protection Schemes Act",
    "Destitute Persons Act",
    "Development Fund Act",
    "Developmental Investment Fund Act",
    "Diplomatic and Consular Officers (Oaths and Fees) Act",
    "Diplomatic and Consular Relations Act",
    "Distress Act",
    "District Cooling Act",
    "District Grand Master of the Eastern Archipelago Ordinance",
    "Early Childhood Development Centres Act 2017 ",
    "Economic Development Board Act",
    "Economic Expansion Incentives (Relief from Income Tax) Act",
    "Education Act",
    "Education Endowment and Savings Schemes Act",
    "Education Service Incentive Payment Act",
    "Electricity Act",
    "Electronic Transactions Act",
    "Employment Act",
    "Employment Agencies Act",
    "Employment Claims Act 2016",
    "Employment of Foreign Manpower Act",
    "Endangered Species (Import and Export) Act",
    "Energy Conservation Act",
    "Energy Market Authority of Singapore Act",
    "Enlistment Act",
    "Enterprise Singapore Board Act 2018",
    "Environmental Protection and Management Act",
    "Environmental Public Health Act",
    "Estate Agents Act",
    "Estate Duty Act",
    "Evidence (Civil Proceedings in Other Jurisdictions) Act",
    "Evidence Act",
    "Exchange Control Act",
    "Exchanges (Demutualisation and Merger) Act",
    "Executive Condominium Housing Scheme Act",
    "Explosive Substances Act",
    "External Loans Act",
    "Extradition Act",
    "Factors Act",
    "Family Justice Act 2014",
    "Federal Lands Commissioner, Malaysia (Incorporation) Act",
    "Feeding Stuffs Act",
    "Fees Act",
    "Films Act",
    "Final Supply (FY 2015) Act 2016",
    "Finance Companies Act",
    "Financial Advisers Act",
    "Financial Procedure Act",
    "Fire Safety Act",
    "Fisheries Act",
    "Foreign Employee Dormitories Act 2015",
    "Foreign Limitation Periods Act",
    "Foreign Recruiting Act",
    "Foreshores Act",
    "Fourth Supplementary Supply (FY 2020) Act 2021",
    "Franciscan Missionaries of the Divine Motherhood Ordinance",
    "Free Trade Zones Act",
    "Frustrated Contracts Act",
    "Gas Act",
    "Geneva Conventions Act",
    "Geographical Indications Act 2014",
    "Good Shepherd Nuns Ordinance",
    "Goods and Services Tax Act",
    "Goods and Services Tax Voucher Fund Act",
    "Government Contracts Act",
    "Government Proceedings Act",
    "Government Procurement Act",
    "Government Securities Act",
    "Government Technology Agency Act 2016",
    "Guardianship of Infants Act",
    "Hazardous Waste (Control of Export, Import and Transit) Act",
    "Health Products Act",
    "Health Promotion Board Act",
    "Health Sciences Authority Act",
    "High Court (Admiralty Jurisdiction) Act",
    "Hijacking of Aircraft and Protection of Aircraft and International Airports Act",
    "Hindu Endowments Act",
    "Hire-Purchase Act",
    "Holidays Act",
    "Home Affairs Uniformed Services Superannuation Act",
    "Home Team Corps Act 2017",
    "Home Team Science and Technology Agency Act 2019",
    "Homes for the Aged Act",
    "Hostage-Taking Act",
    "Hotels Act",
    "House to House and Street Collections Act",
    "Housing and Development Act",
    "Housing Developers (Control and Licensing) Act",
    "Human Biomedical Research Act 2015",
    "Human Cloning and Other Prohibited Practices Act",
    "Human Organ Transplant Act",
    "Hydrogen Cyanide (Fumigation) Act",
    "Immigration Act",
    "Income Tax Act",
    "Independence of Singapore Agreement 1965",
    "Industrial Relations Act",
    "Infectious Diseases Act",
    "Info-communications Media Development Authority Act 2016",
    "Infrastructure Protection Act 2017",
    "Inheritance (Family Provision) Act",
    "Inland Revenue Authority of Singapore Act",
    "Innkeepers Act",
    "Inquiries Act",
    "Insolvency, Restructuring and Dissolution Act 2018",
    "Institute of Technical Education Act",
    "Insurance Act",
    "Intellectual Property (Border Enforcement) Act 2018 ",
    "Intellectual Property (Dispute Resolution) Act 2019",
    "Intellectual Property Office of Singapore Act",
    "Internal Security Act",
    "International Arbitration Act",
    "International Child Abduction Act",
    "International Development Association Act",
    "International Finance Corporation Act",
    "International Interests in Aircraft Equipment Act",
    "International Organisations (Immunities and Privileges) Act",
    "Internationally Protected Persons Act",
    "Interpretation Act",
    "Intestate Succession Act",
    "Intoxicating Substances Act",
    "ISEAS – Yusof Ishak Institute Act",
    "Jewish Synagogue Ordinance",
    "Judges’ Remuneration Act",
    "Judicial Proceedings (Regulation of Reports) Act",
    "Jurong Town Corporation Act",
    "Kidnapping Act",
    "Land Acquisition Act",
    "Land Revenue Collection Act",
    "Land Surveyors Act",
    "Land Titles (Strata) Act",
    "Land Titles Act",
    "Land Transport Authority of Singapore Act",
    "Layout-Designs of Integrated Circuits Act",
    "Legal Aid and Advice Act",
    "Legal Profession Act",
    "Legitimacy Act",
    "Lifelong Learning Endowment Fund Act",
    "Limitation Act",
    "Limited Liability Partnerships Act",
    "Limited Partnerships Act",
    "Liquor Control (Supply and Consumption) Act 2015",
    "Little Sisters of the Poor Ordinance",
    "Loans (International Banks) Act",
    "Local Forces (Relief of Financial Hardship) Act",
    "Local Treasury Bills Act",
    "Maintenance of Parents Act",
    "Maintenance of Religious Harmony Act",
    "Maintenance Orders (Reciprocal Enforcement) Act",
    "Manufacture of Optical Discs Act",
    "Marine Insurance Act",
    "Maritime and Port Authority of Singapore Act",
    "Maritime Conventions Act 1911",
    "Maritime Offences Act",
    "Massage Establishments Act 2017",
    "Mediation Act 2017",
    "Medical (Therapy, Education and Research) Act",
    "Medical and Elderly Care Endowment Schemes Act",
    "Medical Registration Act",
    "Medicines (Advertisement and Sale) Act",
    "Medicines Act",
    "MediShield Life Scheme Act 2015",
    "Mental Capacity Act",
    "Mental Health (Care and Treatment) Act",
    "Mercantile Law Amendment Act",
    "Merchant Shipping (Civil Liability and Compensation for Bunker Oil Pollution) Act",
    "Merchant Shipping (Civil Liability and Compensation for Oil Pollution) Act",
    "Merchant Shipping (Maritime Labour Convention) Act 2014",
    "Merchant Shipping (Wreck Removal) Act 2017",
    "Merchant Shipping Act",
    "Methodist Episcopal Location Board Ordinance",
    "Metrication Act",
    "Military Manoeuvres Act",
    "Minister for Finance (Incorporation) Act",
    "Minors’ Contracts Act",
    "Miscellaneous Offences (Public Order and Nuisance) Act",
    "Misrepresentation Act",
    "Missions Étrangères Ordinance",
    "Misuse of Drugs Act",
    "Monetary Authority of Singapore Act",
    "Moneylenders Act",
    "Motor Vehicles (Third-Party Risks and Compensation) Act",
    "Multi-Level Marketing and Pyramid Selling (Prohibition) Act",
    "Mutual Assistance in Criminal Matters Act",
    "Mutual Benefit Organisations Act",
    "Nanyang Polytechnic Act",
    "Nanyang Technological University (Corporatisation) Act",
    "National Arts Council Act",
    "National Cadet Corps Act",
    "National Council of Social Service Act",
    "National Emblems (Control of Display) Act",
    "National Environment Agency Act",
    "National Heritage Board Act",
    "National Library Board Act",
    "National Parks Board Act",
    "National Productivity Fund Act",
    "National Registration Act",
    "National Registry of Diseases Act",
    "National Research Fund Act",
    "National Servicemen (Employment) Act",
    "National University of Singapore (Corporatisation) Act",
    "Newspaper and Printing Presses Act",
    "Ngee Ann Kongsi (Incorporation) Ordinance",
    "Ngee Ann Polytechnic Act",
    "Notaries Public Act",
    "Nurses and Midwives Act",
    "Oaths and Declarations Act",
    "Official Secrets Act",
    "Optometrists and Opticians Act",
    "Organised Crime Act 2015",
    "Parking Places (Surcharge) Act",
    "Parking Places Act",
    "Parks and Trees Act",
    "Parliament (Privileges, Immunities and Powers) Act",
    "Parliamentary Elections (COVID-19 Special Arrangements) Act 2020",
    "Parliamentary Elections Act",
    "Parliamentary Pensions (Abolition) Act 2012",
    "Parliamentary Pensions Act",
    "Partnership Act",
    "Passports Act",
    "Patents Act",
    "Pawnbrokers Act 2015",
    "Payment and Settlement Systems (Finality and Netting) Act",
    "Payment Services Act 2019",
    "Payroll Tax Act",
    "Penal Code",
    "Pension Fund Act",
    "Pensions (Expatriate Officers) Act",
    "Pensions Act",
    "People’s Association Act",
    "Personal Data Protection Act 2012",
    "Pharmacists Registration Act",
    "Pioneer Generation and Merdeka Generation Funds Act 2014",
    "Planning Act",
    "Plant Varieties Protection Act",
    "Point-to-Point Passenger Transport Industry Act 2019",
    "Poisons Act",
    "Police Force Act",
    "Policies of Assurance Act",
    "Political Donations Act",
    "Portuguese Missions Ordinance",
    "Post Office Savings Bank of Singapore (Transfer of Undertakings and Dissolution) Act",
    "Postal Services Act",
    "Precious Stones and Precious Metals (Prevention of Money Laundering and Terrorism Financing) Act 2019",
    "Presbyterian Church of England Mission Ordinance",
    "Presbyterian Church Ordinance",
    "Preservation of Monuments Act",
    "Presidential Elections Act",
    "Prevention of Corruption Act",
    "Prevention of Human Trafficking Act 2014",
    "Prevention of Pollution of the Sea Act",
    "Price Control Act",
    "Prisons Act",
    "Private Education Act",
    "Private Hospitals and Medical Clinics Act",
    "Private Lotteries Act",
    "Private Security Industry Act",
    "Probate and Administration Act",
    "Probation of Offenders Act",
    "Professional Engineers Act",
    "Property Tax Act",
    "Protection from Harassment Act",
    "Protection from Online Falsehoods and Manipulation Act 2019",
    "Public Entertainments Act",
    "Public Order Act",
    "Public Order and Safety (Special Powers) Act 2018",
    "Public Sector (Governance) Act 2018",
    "Public Service (Monthly Variable Component and Non-pensionable Annual Allowance) Act",
    "Public Service Commission and Legal Service Commission Act",
    "Public Transport Council Act",
    "Public Trustee Act",
    "Public Utilities Act",
    "Radiation Protection Act",
    "Railways Act",
    "Rapid Transit Systems Act",
    "Reciprocal Enforcement of Commonwealth Judgments Act",
    "Reciprocal Enforcement of Foreign Judgments Act",
    "Redemptorist Fathers Ordinance",
    "Registered Designs Act",
    "Registration of Births and Deaths Act",
    "Registration of Criminals Act",
    "Registration of Deeds Act",
    "Regulation of Imports and Exports Act",
    "Remote Gambling Act 2014",
    "Republic of Singapore Independence Act",
    "Republic Polytechnic Act",
    "Requisition of Resources Act",
    "Residential Property Act",
    "Resource Sustainability Act 2019",
    "Retirement and Re-employment Act",
    "Revised Edition of the Laws Act",
    "Revised Supplementary Supply (FY 2020) Act 2020",
    "Road Traffic Act",
    "Road Vehicles (Special Powers) Act",
    "Roman Catholic Archbishop Act",
    "Rubber Industry Act",
    "Saint Andrew’s Mission Hospital Ordinance",
    "Sale of Commercial Properties Act",
    "Sale of Drugs Act",
    "Sale of Food Act",
    "Sale of Goods (United Nations Convention) Act",
    "Sale of Goods Act",
    "Salvation Army Ordinance",
    "Sand and Granite Quarries Act",
    "Scheut Missions Ordinance",
    "School Boards (Incorporation) Act",
    "School Crossing Patrols Act",
    "Science Centre Act",
    "Second Supplementary Supply (FY 2020) Act 2020",
    "Secondhand Goods Dealers Act",
    "Secretary of the Synod of the Diocese of Singapore Ordinance",
    "Securities and Futures Act",
    "Sedition Act",
    "Sentosa Development Corporation Act",
    "Service Lands Act",
    "Settled Estates Act",
    "Sewerage and Drainage Act",
    "Shared Mobility Enterprises (Control and Licensing) Act 2020",
    "Significant Infrastructure Government Loan Act 2021",
    "Silver Support Scheme Act 2015",
    "Singapore Academy of Law Act",
    "Singapore Accountancy Commission Act",
    "Singapore Armed Forces Act",
    "Singapore Arms and Flag and National Anthem Act",
    "Singapore Business Federation Act",
    "Singapore Convention on Mediation Act 2020",
    "Singapore Corporation of Rehabilitative Enterprises Act",
    "Singapore Examinations and Assessment Board Act",
    "Singapore Food Agency Act 2019 ",
    "Singapore Institute of Technology Act",
    "Singapore Labour Foundation Act",
    "Singapore Land Authority Act",
    "Singapore Management University Act",
    "Singapore Polytechnic Act",
    "Singapore Railway Transfer Ordinance",
    "Singapore Red Cross Society Act",
    "Singapore Sports Council Act",
    "Singapore Totalisator Board Act",
    "Singapore Tourism (Cess Collection) Act",
    "Singapore Tourism Board Act",
    "Singapore University of Social Sciences Act 2017 ",
    "Singapore University of Technology and Design Act",
    "Skills Development Levy Act",
    "SkillsFuture Singapore Agency Act 2016",
    "Small Claims Tribunals Act",
    "Small Motorised Vehicles (Safety) Act 2020",
    "Smoking (Prohibition in Certain Places) Act",
    "Societies Act",
    "Society of Saint Maur Incorporation Ordinance",
    "Spam Control Act",
    "Stamp Duties Act",
    "State Courts Act",
    "State Immunity Act",
    "State Lands Act",
    "State Lands Encroachments Act",
    "States of Malaya Customs Duties Collection Act",
    "Statistics Act",
    "Status of Children (Assisted Reproduction Technology) Act",
    "Statute Law Reform Act 2021",
    "Statutory Boards (Taxable Services) Act",
    "Statutory Bodies and Government Companies (Protection of Secrecy) Act",
    "Statutory Corporations (Contributions to Consolidated Fund) Act",
    "Straits Settlements and Johore Territorial Waters (Agreement) Act 1928",
    "Strategic Goods (Control) Act",
    "Street Works Act",
    "Sultan Hussain Ordinance",
    "Supplementary Supply (FY 2016) Act 2017",
    "Supplementary Supply (FY 2017) Act 2018",
    "Supplementary Supply (FY 2018) Act 2019",
    "Supplementary Supply (FY 2019) Act 2020",
    "Supply Act 2016",
    "Supply Act 2017",
    "Supply Act 2018",
    "Supply Act 2019",
    "Supply Act 2020",
    "Supply Act 2021",
    "Supply of Goods Act",
    "Supreme Court of Judicature Act",
    "Telecommunications Act",
    "Temasek Polytechnic Act",
    "Termination of Pregnancy Act",
    "Terrorism (Suppression of Bombings) Act",
    "Terrorism (Suppression of Financing) Act",
    "Terrorism (Suppression of Misuse of Radioactive Material) Act 2017",
    "The Kwong-Wai-Shiu Free Hospital (Transfer of Undertaking and Dissolution) Act 2017",
    "Third Parties (Rights Against Insurers) Act",
    "Third Supplementary Supply and Budget Adjustments (FY 2020) Act 2020",
    "Tobacco (Control of Advertisements and Sale) Act",
    "Tokyo Convention Act",
    "Town Councils Act",
    "Trade Disputes Act",
    "Trade Marks Act",
    "Trade Unions Act",
    "Traditional Chinese Medicine Practitioners Act",
    "Transboundary Haze Pollution Act 2014",
    "Travel Agents Act",
    "Treasurer of Presbyterian Church, Singapore Ordinance",
    "Treasury Deposit Receipts Act",
    "Trust Companies Act",
    "Trustees Act",
    "Undesirable Publications Act",
    "Unfair Contract Terms Act",
    "United Nations Act",
    "United Nations Personnel Act",
    "Urban Redevelopment Authority Act",
    "Vandalism Act",
    "Variable Capital Companies Act 2018",
    "Victoria Theatre Act",
    "Vigilante Corps Act",
    "Visiting Forces Act",
    "Voluntary Sterilization Act",
    "Vulnerable Adults Act 2018 ",
    "Weights and Measures Act",
    "Wholesome Meat and Fish Act",
    "Widows’ and Orphans’ Pension Act",
    "Wildlife Act",
    "Wills Act",
    "Women’s Charter",
    "Work Injury Compensation Act 2019",
    "Workforce Singapore Agency Act",
    "Workplace Safety and Health Act"
];
